name: Scan Application Code with Semgrep SAST

on:
  pull_request: {}
  workflow_dispatch:
    inputs:
      xss_config:
        description: 'Path to Semgrep configuration file'
        required: true
      xss_output:
        description: 'Path to Semgrep output file'
        required: true
      ci_config:
        description: 'Path to Semgrep configuration file'
        required: true
      ci_output:
        description: 'Path to Semgrep output file'
        required: true
  push:
    branches: ["main", "development"]

jobs:
  semgrep:
    name: Scan Application Code with Semgrep SAST
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    container:
      image: returntocorp/semgrep:latest

    if: github.actor != 'dependabot[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Semgrep XSS Scan
      run: semgrep --config ${{ inputs.xss_config }} --sarif --output=${{ inputs.xss_output }}
      continue-on-error: true

    - name: Run Semgrep High-Confidence SAST Scan
      run: semgrep --config ${{ inputs.ci_config }} --sarif --output=${{ inputs.ci_output }}
      continue-on-error: true

    - name: Upload XSS SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ inputs.xss_output }}
        category: "Semgrep XSS Scan"

    - name: Upload CI SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ inputs.ci_output }}
        category: "Semgrep High-Confidence SAST Scan"
