name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - development

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Create .env file
        run: echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" > .env  

      - name: Build and Run SonarQube with Docker Compose
        run: docker-compose up -d

      - name: Run SonarScanner
        run: |
          docker-compose run sonar-scanner

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
