name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11 (Required for SonarQube)
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: 'jdk'

      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.0.4578-linux.zip
          unzip sonar-scanner-cli-6.2.0.4578-linux.zip -d $HOME
          export PATH="$HOME/sonar-scanner-6.2.0.4578-linux/bin:$PATH"

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=mutillidae \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN
